### ISSUE TITLE
Inconsistent text position in output image frames, text appears to move.

### ISSUE THREAD

**Issue by tscott0** [jpoz/gomeme#1]
Hi, I have included both the input and output images below. The output image has the text in each frame of the gif but the text is not always in the same place. I can only assume the input gif has some weird frames but not really sure. 

The gif was generated using the following command:
`gomeme -b "Weird artifact..." picardwave.gif hello.gif`

![picardwave](https://cloud.githubusercontent.com/assets/14017974/20677073/d3d266da-b589-11e6-8892-d66ad0596c46.gif)
![hello](https://cloud.githubusercontent.com/assets/14017974/20677074/d3dd1fda-b589-11e6-89c8-3834b21bca79.gif)

**Comment by jpoz** [comment]
Whoa! I kind of like the output :) but I'll look into fixing it.

**Comment by jpoz** [comment]
![hello](https://cloud.githubusercontent.com/assets/12866/20742855/a954b300-b687-11e6-93ed-4fc807b372fd.gif)

**Comment by tscott0** [comment]
My hero!
